In [1]:
import pandas as pd

In [2]:
pe2se = pd.read_csv("./mappings/pe2se.csv", sep=";")
pe2se

,REMIND name,dataset name,dataset reference product,dataset unit,share
0,pegas.seel.ngcc,"electricity production, natural gas, combined ...","electricity, high voltage",kilowatt hour,1.0
1,pegas.seel.ngccc,"electricity production, at natural gas-fired c...","electricity, high voltage",kilowatt hour,1.0
2,pegas.seel.ngt,"electricity production, natural gas, conventio...","electricity, high voltage",kilowatt hour,1.0
3,pegas.seel.gaschp,"heat and power co-generation, natural gas, com...","electricity, high voltage",kilowatt hour,regional
4,pegas.seel.gaschp,"heat and power co-generation, natural gas, com...","heat, district or industrial, natural gas",megajoule,regional
...,...,...,...,...,...
74,pesol.seel.csp,"electricity production, solar tower power plan...","electricity, high voltage",kilowatt hour,0.5
75,pesol.seel.csp,"electricity production, solar thermal paraboli...","electricity, high voltage",kilowatt hour,0.5
76,pesol.sehe.solhe,"operation, solar collector system, Cu flat pla...","heat, central or small-scale, other than natur...",megajoule,1.0
77,peur.seel.tnrs,"electricity production, nuclear, pressure wate...","electricity, high voltage",kilowatt hour,1.0
78,peur.seel.fnrs,"electricity production, nuclear, pressure wate...","electricity, high voltage",kilowatt hour,1.0

In [5]:
pe2se["all_te"] = pe2se["REMIND name"].apply(lambda x: x.split(".")[-1])

In [7]:
pe2se[["all_te", "dataset name", "dataset reference product", "dataset unit", "share"]].to_csv("./mappings/pe2se.csv", sep=";", index=False)

In [2]:
prodse = pd.read_csv("../internalizer/data/mappings/prodSE.csv", sep=";")
prodse

,REMIND index,dataset name,dataset reference product,dataset unit,share
0,pegas.seel.ngcc,"electricity production, natural gas, combined ...","electricity, high voltage",kilowatt hour,1.0
1,pegas.seel.ngccc,"electricity production, at natural gas-fired c...","electricity, high voltage",kilowatt hour,1.0
2,pegas.seel.ngt,"electricity production, natural gas, conventio...","electricity, high voltage",kilowatt hour,1.0
3,pegas.seel.gaschp,"heat and power co-generation, natural gas, com...","electricity, high voltage",kilowatt hour,regional
4,pegas.seel.gaschp,"heat and power co-generation, natural gas, com...","heat, district or industrial, natural gas",megajoule,regional
...,...,...,...,...,...
82,seh2.seel.h2turb,"electricity production, from hydrogen-fired on...","electricity, high voltage",kilowatt hour,1.0
83,seh2.segasyn.h22ch4,"methane, from electrochemical methanation, wit...","methane, from electrochemical methanation",kilogram,0.5
84,seh2.segasyn.h22ch4,"methane, from electrochemical methanation, wit...","methane, from electrochemical methanation",kilogram,0.5
85,seh2.seliqsyn.MeOH,"diesel production, synthetic, Fischer Tropsch ...","diesel, synthetic",kilogram,0.5
86,seh2.seliqsyn.MeOH,"kerosene production, synthetic, Fischer Tropsc...","kerosene, synthetic",kilogram,0.5

In [3]:
prodse["REMIND index"] = prodse["REMIND index"].apply(lambda x: x.split(".")[-1])

In [4]:
prodse.to_csv("../internalizer/data/mappings/prodSE.csv", sep=";", index=False)

In [5]:
pd.concat([])

ValueError: No objects to concatenate